// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfekhaqqwnxgefzpsbuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmZWtoYXFxd254Z2VmenBzYnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNTM4MzAsImV4cCI6MjA2NDgyOTgzMH0.i1ksaB3MA_NVH30RQy5BmPPxmGXe5v7rYgXONUxiDL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);